
def myFun(name,age):
    print("Name is : ",name)
    print("age is : ",age)
    print("================")

#calling
#myFun() TypeError
myFun("sai",23)
myFun(23,"sai")
